# Generated by Django 3.2.4 on 2023-02-08 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DesignPrinciple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principle1', models.IntegerField(default=None)),
                ('principle2', models.IntegerField(default=None)),
                ('principle3', models.IntegerField(default=None)),
                ('principle4', models.IntegerField(default=None)),
                ('principle5', models.IntegerField(default=None)),
                ('principle6', models.IntegerField(default=None)),
                ('principle7', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('age', models.PositiveIntegerField(default=18)),
                ('gender', models.TextField(default='')),
                ('preferred_writing_language', models.TextField(default='')),
                ('preferred_reading_language', models.TextField(default='')),
                ('country', models.TextField(default='')),
                ('nationality', models.TextField(default='')),
                ('ethnicity', models.TextField(default='')),
                ('text_directionality', models.TextField(default='')),
                ('internet_stability', models.TextField(default='')),
                ('broadband_contract', models.TextField(default='')),
                ('age_first_used_technology', models.PositiveIntegerField(default=18)),
                ('competency_level', models.TextField(default='')),
                ('age_when_first_owned_device', models.PositiveIntegerField(default=18)),
                ('device_ownership_status', models.TextField(default='')),
                ('device_sharing_status', models.TextField(default='')),
                ('device_type_owned', models.TextField(default='')),
                ('device_access', models.TextField(default='')),
                ('client_id', models.CharField(default=None, max_length=100, primary_key=True, serialize=False)),
                ('design_principles', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='survey.designprinciple')),
            ],
        ),
    ]
