# Generated by Django 3.2.4 on 2023-02-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='description',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='title',
        ),
        migrations.AddField(
            model_name='survey',
            name='age',
            field=models.PositiveIntegerField(default=18),
        ),
        migrations.AddField(
            model_name='survey',
            name='ageForDevice',
            field=models.PositiveIntegerField(default=18),
        ),
        migrations.AddField(
            model_name='survey',
            name='ageForTech',
            field=models.PositiveIntegerField(default=18),
        ),
        migrations.AddField(
            model_name='survey',
            name='broadbandContract',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='survey',
            name='competency',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='survey',
            name='country',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='survey',
            name='designPrinciples',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='survey',
            name='deviceAccess',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='survey',
            name='deviceOwnership',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='survey',
            name='deviceShare',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='survey',
            name='deviceTypeOwnership',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='survey',
            name='ethnicity',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='survey',
            name='gender',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='survey',
            name='internetStability',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='survey',
            name='languageToRead',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='survey',
            name='languageToWrite',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='survey',
            name='nationality',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='survey',
            name='textDirectionality',
            field=models.TextField(default=''),
        ),
    ]
