# Generated by Django 3.2.4 on 2023-02-12 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20230212_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='age',
            field=models.TextField(default='18-19'),
        ),
    ]
