# Generated by Django 3.2.4 on 2023-03-01 13:18

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_survey_nationality_from_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantevaluation',
            name='correlation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='participantevaluation',
            name='generalisability',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='participantevaluation',
            name='representation_of_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='survey',
            name='age',
            field=django_cryptography.fields.encrypt(models.TextField(default='18-19')),
        ),
    ]
