# Generated by Django 3.2.4 on 2023-02-13 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_alter_survey_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('role', models.TextField(default='')),
                ('client_id', models.CharField(default=None, max_length=100, primary_key=True, serialize=False)),
                ('consent_form', models.BooleanField(default=False)),
                ('usefulness_for_profession', models.TextField(default='')),
                ('usefulness_for_researcher', models.TextField(default='')),
                ('design_for_non_western', models.TextField(default='')),
                ('design_for_western', models.TextField(default='')),
                ('feedback', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='survey',
            name='consent_form',
            field=models.BooleanField(default=False),
        ),
    ]
