# Generated by Django 3.2.4 on 2023-02-20 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20230213_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlation', models.TextField(default='')),
                ('no_correlation_reason', models.TextField(blank=True, default='')),
                ('correlation_culture', models.BooleanField(default=False)),
                ('no_correlation_culture_reason', models.TextField(blank=True, default='')),
                ('representation_of_user', models.TextField(default='')),
                ('no_representation_reason', models.TextField(blank=True, default='')),
                ('generalisability', models.TextField(default='')),
                ('no_generalisability_reason', models.TextField(blank=True, default='')),
            ],
        ),
    ]
