# Generated by Django 4.1.7 on 2023-03-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantevaluation',
            name='id',
        ),
        migrations.AddField(
            model_name='participantevaluation',
            name='client_id',
            field=models.CharField(default=None, max_length=100, primary_key=True, serialize=False),
        ),
    ]
